# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
#---START: EXAMPLE USING TASK FOR MAVEN
- task: Maven@3
  inputs:
    mavenPomFile: '$(system.defaultWorkingDirectory)/ConfigFiles/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
#---END: EXAMPLE USING TASK FOR MAVEN
#---START: EXAMPLE USING SCRIPT TASK (MAVEN). It is not possible to send arguments to start JVM
#- script: |
#    echo Starting the build
#    mvn package -f ConfigFiles/pom.xml
#  displayName: 'Build with Maven'
##---END: EXAMPLE USING SCRIPT TASK (MAVEN).